import { createStitches, PropertyValue, ScaleValue, CSS as StitchesCSS } from '@stitches/react';

import {
  gray,
  mauve,
  slate,
  sage,
  olive,
  sand,
  grayDark,
  mauveDark,
  slateDark,
  sageDark,
  oliveDark,
  sandDark,
  tomato,
  red,
  crimson,
  pink,
  plum,
  purple,
  violet,
  indigo,
  blue,
  cyan,
  teal,
  green,
  grass,
  brown,
  orange,
  tomatoDark,
  redDark,
  crimsonDark,
  pinkDark,
  plumDark,
  purpleDark,
  violetDark,
  indigoDark,
  blueDark,
  cyanDark,
  tealDark,
  greenDark,
  grassDark,
  brownDark,
  orangeDark,
  sky,
  mint,
  lime,
  yellow,
  amber,
  skyDark,
  mintDark,
  limeDark,
  yellowDark,
  amberDark,
  gold,
  bronze,
  goldDark,
  bronzeDark,
} from '@radix-ui/colors';

const spacing = {
  1: '0.25rem',
  2: '0.5rem',
  3: '0.75rem',
  4: '1rem',
  5: '1.25rem',
  6: '1.5rem',
  7: '1.75rem',
  8: '2rem',
  9: '2.25rem',
  10: '2.5rem',
  11: '2.75rem',
  12: '3rem',
  14: '3.5rem',
  16: '4rem',
  20: '5rem',
  24: '6rem',
  28: '7rem',
  32: '8rem',
  36: '9rem',
  40: '10rem',
  44: '11rem',
  48: '12rem',
  52: '13rem',
  56: '14rem',
  60: '15rem',
  64: '16rem',
  72: '18rem',
  80: '20rem',
  96: '24rem',
};

export const { styled, css, config, theme, createTheme, reset, getCssText, globalCss, keyframes } =
  createStitches({
    theme: {
      colors: {
        // neutrals
        ...gray,
        ...mauve,
        ...slate,
        ...sage,
        ...olive,
        ...sand,
        // for white text
        ...tomato,
        ...red,
        ...crimson,
        ...pink,
        ...plum,
        ...purple,
        ...violet,
        ...indigo,
        ...blue,
        ...cyan,
        ...teal,
        ...green,
        ...grass,
        ...brown,
        ...orange,
        // for black text
        ...sky,
        ...mint,
        ...lime,
        ...yellow,
        ...amber,
        // metals
        ...gold,
        ...bronze,

        // ---SEMANTIC TOKENS---

        //neutrals
        appBg: '$slate1',
        bgSubtle: '$slate2',
        bg: '$slate3',
        bgHover: '$slate4',
        bgActive: '$slate5',
        separator: '$slate6',
        subtleBorder: '$slate6',
        border: '$slate7',
        borderHover: '$slate8',
        solid: '$slate9',
        placeholderText: '$slate9',
        solidHover: '$slate10',
        text: '$slate11',
        textHiContrast: '$slate12',

        //accent
        accentBase: '$blue1',
        accentBgSubtle: '$blue2',
        accentBg: '$blue3',
        accentBgHover: '$blue4',
        accentBgActive: '$blue5',
        accentSeparator: '$blue6',
        accentBorder: '$blue7',
        accentBorderHover: '$blue8',
        accentSolid: '$blue9',
        accentSolidHover: '$blue10',
        accentText: '$blue11',
        accentTextHiContrast: '$blue12',

        //success
        successBase: '$grass1',
        successBgSubtle: '$grass2',
        successBg: '$grass3',
        successBgHover: '$grass4',
        successBgActive: '$grass5',
        successSeparator: '$grass6',
        successBorder: '$grass7',
        successBorderHover: '$grass8',
        successSolid: '$grass9',
        successSolidHover: '$grass10',
        successText: '$grass11',
        successTextHiContrast: '$grass12',

        //warning
        warningBase: '$yellow1',
        warningBgSubtle: '$yellow2',
        warningBg: '$yellow3',
        warningBgHover: '$yellow4',
        warningBgActive: '$yellow5',
        warningSeparator: '$yellow6',
        warningBorder: '$yellow7',
        warningBorderHover: '$yellow8',
        warningSolid: '$yellow9',
        warningSolidHover: '$yellow10',
        warningText: '$yellow11',
        warningTextHiContrast: '$yellow12',

        //danger
        dangerBase: '$red1',
        dangerBgSubtle: '$red2',
        dangerBg: '$red3',
        dangerBgHover: '$red4',
        dangerBgActive: '$red5',
        dangerSeparator: '$red6',
        dangerBorder: '$red7',
        dangerBorderHover: '$red8',
        dangerSolid: '$red9',
        dangerSolidHover: '$red10',
        dangerText: '$red11',
        dangerTextHiContrast: '$red12',

        // focus
        focusRing: '$blue8',
      },
      fonts: {
        body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
        heading:
          '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
        mono: 'SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace',
      },
      fontSizes: {
        xs: '0.75rem',
        sm: '0.875rem',
        md: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '4rem',
        '7xl': '4.5rem',
        '8xl': '6rem',
      },
      fontWeights: {
        hairline: 100,
        thin: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
        black: 900,
      },
      lineHeights: {
        none: 1,
        xs: '1rem',
        sm: '1.25rem',
        md: '1.5rem',
        lg: '1.75rem',
        xl: '1.75rem',
        '2xl': '2rem',
        '3xl': '2.25rem',
        '4xl': '2.5rem',
        '5xl': '3rem',
        '6xl': '4rem',
        '7xl': '4.5rem',
        '8xl': '6rem',
      },
      radii: {
        none: '0',
        xs: '0.125rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      zIndices: {
        hide: -1,
        auto: 'auto',
        base: 0,
        docked: 10,
        dropdown: 1000,
        sticky: 1100,
        banner: 1200,
        overlay: 1300,
        modal: 1400,
        popover: 1500,
        skipLink: 1600,
        toast: 1700,
        tooltip: 1800,
      },
      space: {
        ...spacing,
      },
      sizes: {
        ...spacing,
        max: 'max-content',
        min: 'min-content',
        full: '100%',
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
        '8xl': '90rem',
        'container-xs': '$xl',
        'container-sm': '$2xl',
        'container-md': '$3xl',
        'container-lg': '$5xl',
        'container-xl': '$7xl',
      },
    },
    media: {
      light: '(prefers-color-scheme: light)',
      dark: '(prefers-color-scheme: dark)',
      bp1: '(min-width: 280px)',
      bp2: '(min-width: 768px)',
      bp3: '(min-width: 1024px)',
      bp4: '(min-width: 1440px)',
    },
    utils: {
      p: (value: PropertyValue<'padding'>) => ({
        paddingTop: value,
        paddingBottom: value,
        paddingLeft: value,
        paddingRight: value,
      }),
      pt: (value: PropertyValue<'paddingTop'>) => ({
        paddingTop: value,
      }),
      pr: (value: PropertyValue<'paddingRight'>) => ({
        paddingRight: value,
      }),
      pb: (value: PropertyValue<'paddingBottom'>) => ({
        paddingBottom: value,
      }),
      pl: (value: PropertyValue<'paddingLeft'>) => ({
        paddingLeft: value,
      }),
      px: (value: any) => ({
        paddingLeft: value,
        paddingRight: value,
      }),
      py: (value: any) => ({
        paddingTop: value,
        paddingBottom: value,
      }),

      m: (value: PropertyValue<'margin'>) => ({
        marginTop: value,
        marginBottom: value,
        marginLeft: value,
        marginRight: value,
      }),
      mt: (value: PropertyValue<'marginTop'>) => ({
        marginTop: value,
      }),
      mr: (value: PropertyValue<'marginRight'>) => ({
        marginRight: value,
      }),
      mb: (value: PropertyValue<'marginBottom'>) => ({
        marginBottom: value,
      }),
      ml: (value: PropertyValue<'marginLeft'>) => ({
        marginLeft: value,
      }),
      mx: (value: any) => ({
        marginLeft: value,
        marginRight: value,
      }),
      my: (value: any) => ({
        marginTop: value,
        marginBottom: value,
      }),
      bg: (value: PropertyValue<'backgroundColor'>) => ({
        backgroundColor: value,
      }),
      br: (value: PropertyValue<'borderRadius'>) => ({
        borderRadius: value,
      }),
      btrr: (value: ScaleValue<'radii'>) => ({
        borderTopRightRadius: value,
      }),
      bbrr: (value: ScaleValue<'radii'>) => ({
        borderBottomRightRadius: value,
      }),
      bblr: (value: ScaleValue<'radii'>) => ({
        borderBottomLeftRadius: value,
      }),
      btlr: (value: ScaleValue<'radii'>) => ({
        borderTopLeftRadius: value,
      }),
      ox: (value: PropertyValue<'overflowX'>) => ({ overflowX: value }),
      oy: (value: PropertyValue<'overflowY'>) => ({ overflowY: value }),
      boxSize: (value: PropertyValue<'width'>) => ({
        width: value,
        height: value,
      }),
      w: (value: PropertyValue<'width'>) => ({ width: value }),
      h: (value: PropertyValue<'height'>) => ({ height: value }),
      maxW: (value: PropertyValue<'maxWidth'>) => ({ maxWidth: value }),
      maxH: (value: PropertyValue<'maxHeight'>) => ({ maxHeight: value }),
    },
  });

const darkModeConfig = {
  colors: {
    // neutrals
    ...grayDark,
    ...mauveDark,
    ...slateDark,
    ...sageDark,
    ...oliveDark,
    ...sandDark,
    // for white text
    ...tomatoDark,
    ...redDark,
    ...crimsonDark,
    ...pinkDark,
    ...plumDark,
    ...purpleDark,
    ...violetDark,
    ...indigoDark,
    ...blueDark,
    ...cyanDark,
    ...tealDark,
    ...greenDark,
    ...grassDark,
    ...brownDark,
    ...orangeDark,
    // for black text
    ...skyDark,
    ...mintDark,
    ...limeDark,
    ...yellowDark,
    ...amberDark,
    // metals
    ...goldDark,
    ...bronzeDark,

    //ds colors
    appBg: '$slate1',
    bgSubtle: '$slate2',
    bg: '$slate3',
    bgHover: '$slate4',
    bgActive: '$slate5',
    separator: '$slate6',
    subtleBorder: '$slate6',
    border: '$slate7',
    borderHover: '$slate8',
    focus: '$slate8',
    solid: '$slate9',
    solidHover: '$slate10',
    loContrast: '$slate11',
    hiContrast: '$slate12',
  },
};

const globalStyles = globalCss({
  '*, *::before, *::after': {
    boxSizing: 'inherit',
  },
  'html, body': {
    padding: 0,
    margin: 0,
    fontFamily: `-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif`,
  },
});

globalStyles();

export const darkTheme = createTheme('dark-theme', darkModeConfig);
export type CSS = StitchesCSS<typeof config>;
export type { ComponentProps, VariantProps, PropertyValue, ScaleValue } from '@stitches/react';
