name: 'Bug Report'
description: 'File a bug report'
labels: ['Type: Bug 🐛', 'needs triage']
body:
  - type: 'markdown'
    attributes:
      value: |
        Hey, thanks for creating an issue 😄!

        Before you submit, please search open/closed issues since someone might
        have asked the same thing before.

        We also encourage you to post your issue in our [discord](https://discord.gg/Kz9V45WPjG)
        as you may be able to get more timely help from us or another member of the community!
  - type: 'input'
    id: 'expected_behaviour'
    attributes:
      label: '🤔 Expected behaviour'
      description: 'Tell us what should happen.'
      placeholder: |
        When I ____, I expected ____ to happen.
    validations:
      required: true
  - type: 'input'
    id: 'current_behaviour'
    attributes:
      label: '😯 Current Behavior'
      description: 'Tell us what happens instead of the expected behavior.
        If you are seeing an error, please include the full error message and stack trace.'
      placeholder: |
        When I ____, ____ happened instead.
    validations:
      required: true
  - type: 'input'
    id: 'solution'
    attributes:
      label: '😌 Possible Solution'
      description: 'Not obligatory, but please suggest a fix/reason for the bug if possible.'
      placeholder: |
        I believe ____ may have caused ____ to happen.
  - type: 'input'
    id: 'reproduction'
    attributes:
      label: 'Link to Reproduction'
      description: |
        A link to a codesandbox reproduction which demonstrates the bug.
        You can use the following codesandbox templates to get started: https://github.com/zephyr-ui/zephyr-ui#codesandbox-templates.
      placeholder: 'https://codesandbox.io/'
    validations:
      required: true
  - type: 'textarea'
    id: 'steps'
    attributes:
      label: 'Steps to reproduce'
      description: |
        If you are able to, please explain how to cause the issue in the provided reproduction.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: 'input'
    id: 'zephyr_version'
    attributes:
      label: 'Zephyr UI Version'
      description: 'The version of Zephyr UI you were using when this bug occured.'
      placeholder: '0.1.4'
    validations:
      required: true
  - type: 'input'
    id: 'browser'
    attributes:
      label: 'Browser'
      description: 'The browser(s) this issue occurred with.'
      placeholder: 'Google Chrome 93'
  - type: 'checkboxes'
    id: 'operating-system'
    attributes:
      label: 'Operating System'
      description: 'The operating system(s) this issue occurred with.'
      options:
        - label: 'macOS'
        - label: 'Windows'
        - label: 'Linux'
  - type: 'textarea'
    id: 'additional-context'
    attributes:
      label: 'Additional Context'
      description: |
        Use this section to provide any additional information you might have
        like screenshots, notes, or links to ideas.
